version: "3"

services:
  builder:
    build:
      context: builder
    image: ttmc/ttmc:v1.3.2

  nodeosd:
    build:
      context: .
    image: ttmc/ttmc:v1.3.2
    command: /opt/eosio/bin/nodeosd.sh --data-dir /opt/eosio/bin/data-dir -e --http-alias=nodeosd:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    hostname: nodeosd
    ports:
      - 8888:8888
      - 9876:9876
    expose:
      - "8888"
    volumes:
      - ttmc-nodeos-data-volume:/opt/eosio/bin/data-dir
      - ./config2.ini:/opt/eosio/bin/data-dir/config.ini
    cap_add:
      - IPC_LOCK
    stop_grace_period: 10m

  keosd:
    image: ttmc/ttmc:v1.3.2
    command: /opt/eosio/bin/keosd --wallet-dir /opt/eosio/bin/data-dir --http-server-address=127.0.0.1:8900 --http-alias=keosd:8900 --http-alias=localhost:8900
    hostname: keosd
    links:
      - nodeosd
    volumes:
      - ttmc-keosd-data-volume:/opt/eosio/bin/data-dir
    stop_grace_period: 10m

volumes:
  ttmc-nodeos-data-volume:
    external: true
  ttmc-keosd-data-volume:
    external: true
